appConfig:
  name: "ARENA2036 EDC Management Console"
  client_id: "CX-EDC"
  version: "1.0.0"
  port: "${APP_PORT}"
  host: "${APP_HOST}"

authorization:
  enabled: "${AUTH_ENABLED}"
  apiKey:
    key: "${API_KEY_HEADER}"
    value: "${API_KEY_VALUE}"

startup:
  checks: true
  refresh_interval: 10

dataspaceConfig:
  name: "ARENA2036-X"
  authority_id: "${DATASPACE_AUTHORITY_ID}"

  centralidp:
    url: "${CENTRALIDP_URL}"
    realm: "${CENTRALIDP_REALM}"
    client_id: "${CENTRALIDP_CLIENT_ID}"
    client_secret: "${CENTRALIDP_CLIENT_SECRET}"

  ssi_wallet:
    url: "${SSI_WALLET_URL}"
    client_id: "${SSI_WALLET_CLIENT_ID}"
    client_secret: "${SSI_WALLET_CLIENT_SECRET}"

  portal:
    url: "${PORTAL_URL}"
    client_id: "${PORTAL_CLIENT_ID}"
    client_secret: "${PORTAL_CLIENT_SECRET}"

  discovery:
    semantics:
      url: "${SEMANTICS_URL}"

    discoveryFinder:
      endpoint: "/discoveryfinder/api/v1.0/administration/connectors/discovery/search"

      keys:
        edc_discovery: "bpn"

      client_id: "${DISCOVERY_FINDER_CLIENT_ID}"
      client_secret: "${DISCOVERY_FINDER_CLIENT_SECRET}"

    bpnDiscovery:
      endpoint: "/bpndiscovery/api/v1.0/administration/connectors/bpnDiscovery/search"
      client_id: "${BPN_DISCOVERY_CLIENT_ID}"
      client_secret: "${BPN_DISCOVERY_CLIENT_SECRET}"

clusterConfig:
  context: "${CLUSTER_CONTEXT}"
  namespace: "${CLUSTER_NAMESPACE}"

sde:
  url: "${SDE_URL}"
  client_id: "${SDE_CLIENT_ID}"
  manufacturerId: "${SDE_MANUFACTURER_ID}"
  providerEDC: "${SDE_PROVIDER_EDC}"
  consumerEDC: "${SDE_CONSUMER_EDC}"
  registryUrl: "${SDE_REGISTRY_URL}"

edc:
  default_url: "${EDC_DEFAULT_URL}"
  helm_chart_directory: "./tractusx-connector"

  endpoints:
    assets: "/v3/assets"
    policies: "/v3/policydefinitions"
    contracts: "/v3/contractdefinitions"
    readiness: "/api/check/readiness"
    liveness: "/api/check/liveness"
    catalog: "/management/v3/catalog/request"
    edr_prefix: "/management/v3/edrs"
    view_edr: "/request"
    transfer_edr: "/dataaddress?auto_refresh=true"
    dsp: "/api/v1/dsp"

  hostname:
    cp: "${EDC_HOSTNAME_CP}"
    dp: "${EDC_HOSTNAME_DP}"

database:
  url: "${DATABASE_URL}"
  echo: false

files:
  charts:
    v9: /Chart_v9.yaml
    v10: /Chart_v10.yaml
    v11: /Chart_v11.yaml

  values:
    v9: /values_v9.yaml
    v10: /values_v10.yaml
    v11: /values_v11.yaml