# Default values for edc-management-console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
name: "edc-management-console"
nameOverride: ""
fullnameOverride: "emc-5"

backend:
  enabled: true
  name: "emc-backend-5"
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    # repository: nginx
    repository: "arena2036.azurecr.io/emc-backend"
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "txcd-latest"
  envFrom:
    - secretRef:
        name: emc-azure-credentials
  ingress:
    enabled: true
    ingressClassName: "webapprouting.kubernetes.azure.com"
    # className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: &hostname "emc-backend-5-txcd.arena2036-x.de"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: emc-backend-5-tls
        hosts:
          - *hostname

  # -- Existing image pull secret to use to [obtain the container image from private registries](https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry)
  imagePullSecrets:
    - name: acr-pull-secret
  podAnnotations: {}
    # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: ClusterIP
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 8001


  configuration:
    yml: |-
      appConfig:
        name: "ARENA2036 EDC Management Console"
        client_id: "EMC-5"
        version: "1.0.0"
        port: 5000
        host: "0.0.0.0"

      authorization:
        enabled: true
        apiKey:
          key: "X-Api-Key"
          value: "emc-api-key"

      startup:
        checks: true
        refresh_interval: 10

      dataspaceConfig:
        name: "ARENA2036-X"
        authority_id: "BPNL00000003CRHK"
        centralidp:
          url: "https://centralidp-txcd.arena2036-x.de/auth/"
          realm: "CX-Central"
          client_id: "${CENTRALIDP_CLIENT_ID}"
          client_secret: "${CENTRALIDP_CLIENT_SECRET}"
        ssi_wallet:
          url: "https://ssi-dim-wallet-stub-txcd.arena2036-x.de"
          client_id: "sa-cl5-custodian-2"
          client_secret: "changeme"
        portal:
          url: "https://portal-txcd.arena2036-x.de"
          client_id: "sa-cl1-reg-2"
          client_secret: "changeme"
        discovery:
          semantics:
            url: "https://semantics-txcd.arena2036-x.de"
          discoveryFinder:
            endpoint: "/discoveryfinder/api/v1.0/administration/connectors/discovery/search"
            keys:
              edc_discovery: "bpn"
            client_id: "sa-cl21-01"
            client_secret: "changeme"
          bpnDiscovery:
            endpoint: "/bpndiscovery/api/v1.0/administration/connectors/bpnDiscovery/search"
            client_id: "sa-cl22-01"
            client_secret: "changeme"


      clusterConfig:
        context: "arena2036_txcd"
        namespace: "edc-management-console"

      sde:
        url: https://sde-5-txcd.arena2036-x.de
        client_id: "SDE-5"
        manufacturerId: BPNLA360COMPANY5
        providerEDC:  https://emc-edc-5-controlplane-txcd.arena2036-x.de
        consumerEDC: https://emc-edc-6-controlplane-txcd.arena2036-x.de
        registryUrl: https://emc-edc-dtr-5-txcd.arena2036-x.de/semantics/registry

      edc:
        default_url: "https://emc-edc-5-controlplane-txcd.arena2036-x.de"
        helm_chart_directory: "./tractusx-connector"
        endpoints:
          assets: "/v3/assets"
          policies: "/v3/policydefinitions"
          contracts: "/v3/contractdefinitions"
          readiness: "/api/check/readiness"
          liveness: "/api/check/liveness"
          catalog: "/management/v3/catalog/request"
          edr_prefix: "/management/v3/edrs"
          view_edr: "/request"
          transfer_edr: "/dataaddress?auto_refresh=true"
          dsp: "/api/v1/dsp"
        hostname:
          cp: controlplane.arena2036-x.de
          dp: dataplane.arena2036-x.de
  
      database:
        url: "${DATABASE_URL}"
        echo: false
      
      files:
        charts:
          v9: /Chart_v9.yaml
          v10: /Chart_v10.yaml
          v11: /Chart_v11.yaml
        values:
          v9: /values_v9.yaml
          v10: /values_v10.yaml
          v11: /values_v11.yaml

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  ## Additional volumes on the output Deployment definition.
  volumes:
    # -- persist the backend configuration
    - name: emc-backend-config
      configMap:
        name: "{{ .Release.Name }}-emc-backend-config"
    # -- persist the backend data directories
    - name: pvc-emc-backend
      persistentVolumeClaim:
        claimName: "{{ .Release.Name }}-pvc-emc-backend-data"
    # -- temporary file system mount
    - name: tmpfs
      emptyDir: {}
    #  - name: secrets-store
    #    csi:
    #      driver: secrets-store.csi.k8s.io
    #      readOnly: true
    #      volumeAttributes:
    #        secretProviderClass: "secrets-provider

    # -- specifies the volume mounts for the backend deployment
  volumeMounts:
    # -- mounted path for the backend configuration added in the config maps
    - name: emc-backend-config
      mountPath: /backend/config/configuration.yml
      subPath: configuration.yml
    # -- contains the location for the process data directory
    - name: pvc-emc-backend
      mountPath: /backend/data
      subPath: data
    # -- contains the log directory uses by the backend
    - name: tmpfs
      mountPath: /backend/logs
      subPath: logs

frontend:
  enabled: true
  name: "emc-frontend-5"
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    # repository: nginx
    repository: "arena2036.azurecr.io/emc-frontend"
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "txcd-latest"
  imagePullSecrets:
    - name: acr-pull-secret

  env:
    - name: VITE_API_BASE_URL
      value: https://emc-backend-5-txcd.arena2036-x.de
    - name: VITE_API_KEY
      value: emc-api-key
    - name: EDC_HOSTNAME
      value: arena2036-x.de
    - name: VITE_KEYCLOAK_URL
      value: https://centralidp-txcd.arena2036-x.de/auth/
    - name: VITE_KEYCLOAK_REALM
      value: "CX-Central"
    - name: VITE_KEYCLOAK_CLIENT_ID
      value: EMC-5

  configuration: |-
    window.__RUNTIME_CONFIG__ = {
    apiUrl: "https://emc-backend-5-txcd.arena2036-x.de",
    apiKey: "emc-api-key",
    edcHost: "arena2036-x.de",
    keycloakUrl: "https://centralidp-txcd.arena2036-x.de/auth",
    realm: "CX-Central",
    clientId: "EMC-5"
    };

  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    ingressClassName: "webapprouting.kubernetes.azure.com"
    # className: "webapprouting.kubernetes.azure.com"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      # nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: &hostname "emc-5-txcd.arena2036-x.de"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: emc-frontend-5-tls
        hosts:
          - *hostname

  resources: { }
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
  #   cpu: 100m
  #   memory: 128Mi
  volumes:
    # -- persist the frontend configuration
    - name: emc-frontend-config
      configMap:
        name: "{{ .Release.Name }}-emc-frontend-config"

  volumeMounts:
    # -- mounted path for the backend configuration added in the config maps
    - name: emc-frontend-config
      mountPath: /frontend/.env
      subPath: .env

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80


# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /health
    port: 8001
readinessProbe:
  httpGet:
    path: /health
    port: 8001


nodeSelector: {}

tolerations: []

affinity: {}