apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emc-grafana
  namespace: edc-management-console

spec:
  ingressClassName: nginx

  rules:
    - host: grafana.staging.arena2036-x.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emc-grafana
                port:
                  number: 80