name: EMC CI Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  helm-lint:
    name: Helm Lint
    uses: ./.github/workflows/helm-lint.yml

  kics:
    name: KICS Scan
    uses: ./.github/workflows/kics.yaml

  trufflehog:
    name: Secret Scan
    uses: ./.github/workflows/trufflehog.yml

  codeql:
    name: CodeQL
    uses: ./.github/workflows/codeql.yml

  build:
    name: Build Images
    needs:
      - verify
      - helm-lint
      - kics
      - trufflehog
      - codeql
    uses: ./.github/workflows/emc-build.yaml

  # apply-staging-argocd-app:
  #   name: Apply Staging Argo CD App
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref_name == 'staging'

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install kubectl
  #       run: |
  #         echo "Installing kubectl..."
  #         curl -LO -s "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  #         chmod +x kubectl
  #         sudo mv kubectl /usr/local/bin/
  #         kubectl version --client

  #     - name: Install Vault CLI
  #       run: |
  #         curl -sSL https://releases.hashicorp.com/vault/1.21.2/vault_1.21.2_linux_amd64.zip -o vault.zip
  #         unzip vault.zip
  #         chmod +x vault
  #         sudo mv vault /usr/local/bin/
  #         vault --version

  #     - name: Fetch kubeconfig from Vault and connect to cluster
  #       run: |
  #         mkdir -p $HOME/.kube
  #         export VAULT_ADDR="${{ secrets.VAULT_ADDR_STAGING }}"
  #         export VAULT_TOKEN="${{ secrets.VAULT_TOKEN_STAGING }}"
  #         CLUSTER_PATH="staging/infra/cluster-staging"

  #         vault kv get -field=config $CLUSTER_PATH > $HOME/.kube/config
  #         chmod 600 $HOME/.kube/config

  #         CONTEXT=$(yq e '.current-context' $HOME/.kube/config)
  #         echo "Using context: $CONTEXT"

  #         kubectl --context=$CONTEXT cluster-info
  #         echo "KUBE_CONTEXT=$CONTEXT" >> $GITHUB_ENV

  #     - name: Apply Argo CD application
  #       run: |
  #         kubectl --context=$KUBE_CONTEXT apply -f .github/argocd/emc-staging-app.yaml

  #     - name: Check Argo CD application
  #       run: |
  #         kubectl --context=$KUBE_CONTEXT get application emc-staging -n argocd