#################################################################################
# Tractus-X - EDC Management Console
#
# Copyright (c) 2026 ARENA2036 e.V.
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################
---
name:  Edc Management Console Lint and Test Charts

on:
  push:
    branches: ["main", "develop"]
    paths:
      - 'charts/**'

  pull_request:
      paths:
        - charts/**

  workflow_dispatch:
    inputs:
      node_image:
        description: 'kindest/node image for k8s kind cluster'
        default: 'kindest/node:v1.30.0'
        required: false
        type: string
      # # Skip upgrade for now until a working chart is released
      # upgrade_from:
      #   description: 'chart version to upgrade from'
      #   # chart version from 3.2 release as default
      #   default: '0.1.8'
      #   required: false
      #   type: string
      helm_version:
        description: 'helm version to test (default = latest)'
        default: 'latest'
        required: false
        type: string

jobs:
  lint-test:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            with:
              fetch-depth: 0

          - name: Kubernetes KinD Cluster
            uses: container-tools/kind-action@0ad70e2299366b0e1552c7240f4e4567148f723e # v2.0.4
            with:
              # upgrade version, default (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
              version: v0.20.0
              # default value for event_name != workflow_dispatch
              node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.30.0' }}

          - name: Build emc backend image
            uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
            with:
              context: backend
              push: false
              tags: emc-backend:latest

          - name: Build emc frontend image
            uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
            with:
              context: frontend
              push: false
              tags: emc-frontend:latest

          # Load images into Kind
          - name: Load backend image into Kind
            run: kind load docker-image emc-backend:latest

          - name: Load frontend image into Kind
            run: kind load docker-image emc-frontend:latest

          - name: Set up Helm
            uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390 # v4.1.0                      
            with:
              version: v3.12.1

        # Setup python as a prerequisite for chart linting 
          - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
            with:
              python-version: 3.9

          - name: Set up chart-testing
            uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0


          - name: Set target branch
            id: set-target-branch
            run: |
              if [ -n "${{ github.event.pull_request.base.ref }}" ]; then
                echo "target-branch=${{ github.event.pull_request.base.ref }}" >> "$GITHUB_OUTPUT"
              else
                echo "target-branch=${{ github.event.repository.default_branch }}" >> "$GITHUB_OUTPUT"
              fi

          - name: Run chart-testing (list-changed)
            id: list-changed
            run: |
              changed=$(ct list-changed --target-branch ${{ steps.set-target-branch.outputs.target-branch }})
              if [[ -n "$changed" ]]; then
                echo "changed=true" >> $GITHUB_OUTPUT
              fi

          - name: Run chart-testing (lint)
            run: ct lint --validate-maintainers=false --target-branch ${{ steps.set-target-branch.outputs.target-branch }}

          # - name: Run chart-testing (install)
          #   run: ct install --charts charts/edc-management-console
          #   if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'
            
          - name: Run chart-testing (install)
            run: ct install \
                --charts charts/edc-management-console \
                --helm-extra-set-args \
                  --set backend.image.repository=emc-backend \
                  --set backend.image.tag=latest \
                  --set frontend.image.repository=emc-frontend \
                  --set frontend.image.tag=latest

          # Upgrade the released chart version with the locally available chart
          # default value for event_name != workflow_dispatch
          - name: Run helm upgrade
            run: |
              helm repo add bitnami https://charts.bitnami.com/bitnami
              helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
              helm repo update
              helm dependency update charts/edc-management-console
              helm upgrade --install edc charts/edc-management-console
            if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'